import SubQuorum.BandCompensation
import SubQuorum.EndpointCompensation
import SubQuorum.OpposedBandCompensation

#check SubQuorum.BandCompensation.band_blank_surplus
#print axioms SubQuorum.BandCompensation.band_blank_surplus
#check SubQuorum.BandCompensation.parity_matching_band_compensation
#print axioms SubQuorum.BandCompensation.parity_matching_band_compensation
#check SubQuorum.BandCompensation.parity_charge_compensation
#print axioms SubQuorum.BandCompensation.parity_charge_compensation
#check SubQuorum.BandCompensation.one_export_source_compensation
#print axioms SubQuorum.BandCompensation.one_export_source_compensation
#check SubQuorum.EndpointCompensation.terminal_color_balance
#print axioms SubQuorum.EndpointCompensation.terminal_color_balance
#check SubQuorum.EndpointCompensation.one_color_injective_compensation
#print axioms SubQuorum.EndpointCompensation.one_color_injective_compensation
#check SubQuorum.EndpointCompensation.allocation_component
#print axioms SubQuorum.EndpointCompensation.allocation_component
#check SubQuorum.EndpointCompensation.allocation_injective
#print axioms SubQuorum.EndpointCompensation.allocation_injective

#check SubQuorum.OpposedBandCompensation.opposed_band_blank_surplus
#print axioms SubQuorum.OpposedBandCompensation.opposed_band_blank_surplus
#check SubQuorum.OpposedBandCompensation.opposed_matching_compensation
#print axioms SubQuorum.OpposedBandCompensation.opposed_matching_compensation
#check SubQuorum.OpposedBandCompensation.opposed_charge_compensation
#print axioms SubQuorum.OpposedBandCompensation.opposed_charge_compensation
#check SubQuorum.OpposedBandCompensation.two_source_compensation
#print axioms SubQuorum.OpposedBandCompensation.two_source_compensation
